### ISSUE TITLE
AngleTo breaks on the content of CompositeEntity

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#160]

**Comment by AbdelHajou** [comment]
What's the intended behavior for angleTo when dealing with composite entities? Should it use the center or the anchor location?

**Comment by meronbrouwer** [comment]
The current implementation of angleTo is based on the anchorLocation, so it should also do the same for the content of a compositeEntity

**Comment by AbdelHajou** [comment]
As I see it, there are two approaches to fixing this bug:
1. Make getAnchorLocation() of a child entity return the real location instead of the location relative to it's parent.
2. Keep a reference of the parent entity inside the child entity and calculate the real location when calling angleTo().

Are there any other options I'm missing? How would you solve this?

**Comment by meronbrouwer** [comment]
The `Bounded` interface provides a default method:     

```default Bounds getBoundingBox() {
        return getNode().map(node -> node.localToScene(node.getBoundsInLocal(), true)).orElse(EMPTY_BB);
    }```

which returns the bounding box within the Scene. So this one already translates the coordinate system from a composite entity to the scene. I guess we can let angleTo point towards the above method of the "other" entity. This should resolve the bug.
