### ISSUE TITLE
Improve the Debugger

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#17]
Might be usefull: https://github.com/uphy/javafx-console

**Comment by meronbrouwer** [comment]
Note that it might be possible to let this console run on a different thread.

**Comment by sanmai-NL** [comment]
Can we use the [JFR API](https://docs.oracle.com/en/java/javase/14/docs/api/jdk.jfr/jdk/jfr/package-summary.html) to record profiling data instead? It has less of an impact on performance efficiency and it teaches students to use proper tools (from within IntelliJ IDEA) rather than custom components. Moreover, we save ourselves from maintaining a UI for profiling data.

**Comment by meronbrouwer** [comment]
There seems to be no need for improvements, so this task will be closed.
