### ISSUE TITLE
Implement Named animations

### ISSUE THREAD

**Issue by fritzvd** [han-yaeger/yaeger#239]
A sprite sheet of 2 by 3 can be animated at the moment by calling `setAutoCycle(long ms, int row)`

As an enhancement, it would be cool to be able to add parts of a sprite sheet as short animations that can be called later on.

My suggestion would be to add two methods to the DynamicSpriteEntity:

1. `void add(String animationName, int[] animationFrames, long animationSpeedInMs)`
2. `void play(String animationName)`

e.g.

```java
        sprite.add("idle", [0, 1, 2, 3], 30); // add the animation
        sprite.add("walk", [4, 5, 6, 7], 30); // add another animation
        sprite.play("idle"); // play this animation
```

**Comment by meronbrouwer** [comment]
Sounds like a good feature, that's easy to implement. I would prefer to use an Enum instead of a String as identifier.

**Comment by fritzvd** [comment]
Makes sense

**Comment by meronbrouwer** [comment]
This issue is making nice progress. It will, however be implemented without the "named" part.

The approach is that a new Class will be introduced, called Animation, which encapsulates a part of a spritesheet (thus an Animation). These objects can be passed to a new method (playAnimation) and the SpriteAnimationDelegate will handle everything being done correctly.
