### ISSUE TITLE
Newtionian Entities sometime disappear on Collision and keypressed

### ISSUE THREAD

**Issue by meronbrouwer** [han-yaeger/yaeger#245]
This one needs investigation...

**Comment by meronbrouwer** [comment]
@Override
public void onPressedKeysChange(Set<KeyCode> pressedKeys) {
int speed = 3;
if(pressedKeys.contains(KeyCode.LEFT)){
setMotion(speed,270d);
} else if(pressedKeys.contains(KeyCode.RIGHT)){
setMotion(speed,90d);
} else if(pressedKeys.contains(KeyCode.SPACE)){
setMotion(speed,180d);
} else if(pressedKeys.contains(KeyCode.DOWN)){
setMotion(speed,0d);
} else if(pressedKeys.isEmpty()){
// When you let go off the key, you set the speed to 0.
// However, no direction is given for the MotionApplier.
// Therefore, the direction in the MotionApplier is set to NaN.
// This causes the character to disappear.
// setSpeed(0);
// The way to fix this is to use:
setMotion(0, 0);
}
}

**Comment by meronbrouwer** [comment]
This issue cannot be reproduced on my Mac. Could anyone with Windows give it a try?

**Comment by wieberinsma** [comment]
> This issue cannot be reproduced on my Mac. Could anyone with Windows give it a try?

I will try and see if this can be reproduced on Win10.

**Comment by wieberinsma** [comment]
Deze bug mag van mij iets meer context krijgen. Wanneer is deze opgetreden? Komt dit vanuit een Unit-test / draaien van de game?

**Comment by meronbrouwer** [comment]
Deze bug is opgemerkt door een student tijdens het werken aan zijn oopd-game. Veel concreter dan dit heb ik het niet kunnen krijgen. Maar mijn gevoel zegt dat er mogelijk een probleem kan optreden bij het berekenen van de zwaartekrachtersnelling of weerstandvertraging als de snelheid op 0 worst gezet en de Entity nog wel een richting heeft. De student gaf aan dat er dan ergens een NaN verschijnt.

**Comment by wieberinsma** [comment]
The behaviour seems to be non-deterministic. I tested it with the 'Composing' use case from the yaeger-showcase project, using the `onPressedKeysChange()` implementation as mentioned above for UP-DOWN arrow keys. For this use case, there is indeed an issue with `MotionApplier:204`, where the `vector` (this.motion on line 199) is a Coordinate2D (Point2D) with a `NaN` x and y coordinate, resulting in a `NaN` for `currentAngle`. The bug does not occur instantly, sometimes on the first key pressed, sometimes only after several key presses. In addition, it seems `currentAngle` is also `NaN` when x and y coordinates are `0`. It is unclear whether the bug is related to a timing issue, but my guess is it seems so.

**Comment by wieberinsma** [comment]
Just as a guesstimate: could it be that the failure to update the collision results in further key presses to fail also because the system no longer has information on the motion/location of a certain entity? Or should this be isolated? Because after an initial NaN for onPressedKeysChange, any further keys pressed result in a NaN.

**Comment by meronbrouwer** [comment]
It makes sense that an initial NaN leads to more, since all arithmetic operations with a NaN will result in another NaN.
I guess the most likely cause is that at one point some calculcation results in a number that can not be calculated. Baeldung gives a nice overview of the possible causes (https://www.baeldung.com/java-not-a-number) .

**Comment by wieberinsma** [comment]
A little bit more prying seems to indicate the above. In the alternative call stack, `nullifySpeedInDirection` (when key is released) results in a Point2D object with both x and y coordinate for `newMotion` (`MotionApplier:142`). This could be intended, but the result is that on the same line the `convertVectorToAngle(newMotion)` is bound to the new direction, which is `NaN`. Reason for this NaN is a failing arithmetic operation at `Point2D:234` (download sources), due to a division by 0. Specifically, both `ax` and `ay` are 0.
